export class GraphPreferences{
    tempArSide: string = 'left'
    tempMinSide: string = 'left'
    tempMaxSide: string = 'left'
    tempOrvSide: string = 'left'
    chuvaSide: string = 'right'
    direcaoVentoSide: string = 'left'
    velocidadeVentoSide: string = 'right'
    velocidadeVentoMaxSide: string = 'right'
    bateriaSide: string = 'left'
    radiacaoSide: string = 'left'
    pressaoATMSide: string = 'right'
    indiceCalorSide: string = 'left'
    umidadeRelativaSide: string = 'left'
}